apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiapfood-api-producao
  labels:
    app: fiapfood-api-producao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiapfood-producao
  template:
    metadata:
      name: fiapfood-producao
      labels:
        app: fiapfood-producao
    spec:
      containers:
      - name: fiapfood-producao-container
        image: wtof/fiapfood-producao:latest
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: db-producao-secret
        - configMapRef:
            name: api-producao-configmap

        livenessProbe:
          httpGet:
            path: /swagger-ui/index.html
            port: 8081
          periodSeconds: 60
          failureThreshold: 5
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /swagger-ui/index.html
            port: 8081
          periodSeconds: 60
          failureThreshold: 5
          initialDelaySeconds: 180
        resources:
          requests:
            cpu: 200m
            memory: 228Mi
          limits:
            cpu: 400m
            memory: 524Mi
