apiVersion: v1
kind: ConfigMap
metadata:
  name: api-producao-configmap
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-server-fiapfood.mariadb.database.azure.com:3306/fiapfood
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
