version: '3.8'

services:
  app:
    image: wtof/fiapfood-producao:latest
    ports:
      - 8082:8082
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - my_network

networks:
  my_network:
    external:
      name: fiapfood-pedido_my_network