apiVersion: v1
kind: Service
metadata:
  name: fiapfood-producao-service
spec:
  selector:
    app: fiapfood-producao-api
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30003
  type: LoadBalancer
